version: '3.1'

services:
  db:
    container_name: nextjs-prisma-db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nextjs-prisma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nextjs-prisma-network
volumes:
  db-data:
    driver: local

networks:
  nextjs-prisma-network:
    driver: bridge
